config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: :all
  devise_scope :admin do
  get 'admins/sign_in',to: 'admins/sessions#new'
  post 'admins/sign_in',to: 'admins/sessions#create'
  delete 'admins/sign_out',to: 'admins/sessions#destroy'
  end

  devise_for :customers, skip: :all
  devise_scope :customer do
  get 'customers/sign_up', to: 'publics/registrations#new'
  post 'customers/sign_up', to: 'publics/registrations#create'
  patch 'customers', to: 'publics/registrations#update'
  put 'customers', to: 'publics/registrations#update'
  delete 'customers', to: 'publics/registrations#update'
  get 'customers/sign_in',to: 'publics/sessions#new'
  post 'customers/sign_in',to: 'publics/sessions#create'
  delete 'customers/sign_out',to: 'publics/sessions#destroy'
  get 'customers/password/new', to: 'publics/passwords#new'
  get 'customers/password/edit', to: 'publics/passwords#edit'
  patch 'customers/password', to: 'publics/passwords#update'
  put 'customers/password', to: 'publics/passwords#update'
  get 'login' => 'publics/sessions#new', as: :new_customer_session
  post 'login' => 'publics/sessions#create', as: :customer_session
  get 'signup' => 'publics/registrations#new', as: :new_customer_registration
  post 'signup' => 'publics/registrations#create', as: :customer_registration
  get 'password' => 'publics/passwords#new', as: :new_customer_password
  get 'password/edit' => 'publics/passwords#edit', as: :edit_customer_password
  post 'password' => 'publics/passwords#create', as: :customer_password
  #パスワード変更
  get 'password/:id' => 'publics/registrations#edit', as: :edit_customer_registration
  patch "password/:id" => 'publics/registrations#update', as: :update_customer_registration

  end

  root "publics/homes#top"
  get "/about" => "publics/homes#about"
  get "/customers/unsubscribe" => "publics/customers#unsubscribe"
  patch "/customers/withdraw" => "publics/customers#withdraw"
  scope module: :publics do
  get "/customers/unsubscribe" => "customers#unsubscribe"
  patch "/customers/withdraw" => "customers#withdraw"
  get 'password/edit' => 'passwords#edit'
  resources :items, only:[:index, :show]
  get 'genre_items/:id' => "items#genre_items", as: "genre_items"
  get "/orders/complete" => "orders#complete"
  post "/orders/confirm" => "orders#confirm"
  resources :orders, only:[:new, :create, :index, :show]
  delete "/carts/destroy_all" => "carts#destroy_all"
  resources :carts, only:[:index, :update, :destroy, :create]
  resources :customers, only:[:edit, :show, :update]
  resources :addresses, only:[:index, :create, :edit, :destroy, :update]
  end

  namespace :admins do
  get "/" => "homes#top"
  resources :customers, only:[:index, :show, :edit, :update]
  resources :genres, only:[:index, :create, :edit, :update]
  resources :orders, only:[:index, :show, :update]
  resources :items, only:[:index, :new, :create, :show, :edit, :update]
  resources :order_details, only: [:update]
  patch "/orders/:order_id/order_details/:id" => "order_details#update"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details, dependent: :destroy
  belongs_to :customer

  validates :postcode, :address, :name, presence: true

   enum pay_way: {
    クレジット: 0,
    銀行振込: 1
  }

   enum status: {
    入金待ち: 0,
    入金確認: 1,
    製作中: 2,
    発送準備中: 3,
    発送済み: 4
  }

  #validates :order, acceptance: true
  #validates :order, presence: true
  #validates :order, inclusion: {in: [0, 1, 2]}
end

app/controllers/admins/orders_controller.rb
class Admins::OrdersController < ApplicationController
  before_action :authenticate_admin!
  layout 'admins/header'
  def index
    @customer = current_customer
    customer = params[:customer_id]
    if @orders = params[:customer_id]
      order = Order.where(customer_id: customer).all
      orders = order.all.reverse_order
    elsif @orders = params[:created_at]
      range = Date.today.beginning_of_day..Date.today.end_of_day
      order = Order.where(created_at: range)
      orders = order.all.reverse_order
    else
      @orders = Order.all
      orders = Order.all.reverse_order
    end 
      @orders = orders.page(params[:page]).per(10)
  end

  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    @total = 0
  end

  def update
    @order = Order.find(params[:id]) #注文詳細の特定
    @order.update(order_params) #注文ステータスの更新
    if @order.status == "入金待ち"
      OrderDetail.where(order_id: @order.id).update_all(making_status: "製作不可") #注文ステータスが「入金待ち」なら、製作ステータスを「製作不可」に更新
    elsif @order.status == "入金確認"
      OrderDetail.where(order_id: @order.id).update_all(making_status: "製作待ち") #注文ステータスが「入金確認」なら、製作ステータスを「製作待ち」に更新
    end
    redirect_to admins_order_path(@order) #注文詳細へ
  end
  
  private
  def order_params
    params.require(:order).permit(:customer_id, :shipping_cost, :pay_money, :pay_way, :name, :postcode, :address, :status)
  end
end

app/controllers/publics/addresses_controller.rb
class Publics::AddressesController < ApplicationController
  before_action :authenticate_customer!

  layout 'publics/header'
  def index
    address = current_customer.addresses.all
    @addresses = address.page(params[:page]).per(6)
    @address = Address.new
    @customer = current_customer
  end

  def create
    @address = Address.new(address_params)
    @address.customer_id = current_customer.id
    if @address.save
      redirect_to addresses_path #(@address.id)
    else
      @addresses = Address.all
      @customer = current_customer
      render :index
    end
  end

  def edit
    @address = Address.find(params[:id])
    @customer = current_customer
  end

  def destroy
    @address = Address.find(params[:id])
    @address.destroy
    redirect_to addresses_path(@address.id)
  end

  def update
    @address = Address.find(params[:id])
    @address.customer_id = current_customer.id
    if @address.update(address_params)
      redirect_to addresses_path(@address)
    else
      @customer = current_customer
      render :edit
    end
  end

  private
  def address_params
    params.require(:address).permit(:postcode, :address, :name, :customer_id)
  end
end

app/controllers/publics/carts_controller.rb
class Publics::CartsController < ApplicationController
  before_action :authenticate_customer!
  layout 'publics/header'

  def index
    @customer = current_customer
    @carts = @customer.carts.all
    @cart = current_customer.carts.find_by(item_id: params[:item_id])
    @total = 0
  end

  def create
    @customer = current_customer
      # findでparamsの、cartモデルのitem_idを探す
    if Cart.exists?(item_id: @item, customer_id: @customer) # exists?でitem_idとcustomer_idが存在するかを確認する
      @cart = Cart.find_by(item_id: @item.id, customer_id: @customer) # find_byでカートに存在するitem_idとcustomer_idを探す
      @cart.amount += params[:cart][:amount].to_i # カートに存在する商品の数量@cart.amountにparamsでcartモデルのamountを足し、代入する。
      @cart.update(amount: @cart.amount) # 上の行で定義した@cart.amountをupdateする
      redirect_to carts_path
    else
      @cart = Cart.new(cart_params)
      @cart.customer_id = current_customer.id
      if @cart.save
        redirect_to carts_path
      else
        flash[:cart] = "カートに入れる個数を入力してください"
        redirect_back(fallback_location: root_path)
      end
    end
  end

  def update
    @cart = Cart.find(params[:id])
    @cart.update(cart_params)
    if @cart.amount == 0
      @cart.destroy
    end
    redirect_to carts_path
  end

  def destroy
    @cart = Cart.find(params[:id])
    @cart.destroy
    redirect_to carts_path
  end

  def destroy_all
    current_customer.carts.destroy_all
    redirect_to carts_path
  end

  private
  def cart_params
    params.require(:cart).permit(:item_id, :customer_id, :amount)
  end

end

app/controllers/publics/confirmations_controller.rb
# frozen_string_literal: true

class Publics::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/publics/customers_controller.rb
class Publics::CustomersController < ApplicationController
  before_action :authenticate_customer!
  layout 'publics/header'

  def show
    @customer = current_customer
  end

  def edit
    @customer = current_customer
  end

  def update
    @customer = current_customer
    if @customer.update(customer_params)
      redirect_to customer_path(current_customer.id)
    else
      render :edit
    end

  end

  def unsubscribe
    @customer = current_customer
  end

  def withdraw
    @customer = current_customer
    #is_deletedカラムにフラグを立てる（defaultfalse(有効)をtrue(退会済み)にする）
    @customer.update(is_deleted: '退会済み')
    reset_session #ログアウトさせる
    redirect_to root_path
  end

  private
  def customer_params
    params.require(:customer).permit([:first_name, :last_name, :first_name_kana, :last_name_kana, :postcode, :address, :phonenumber, :email])
  end
end

app/controllers/publics/homes_controller.rb
class Publics::HomesController < ApplicationController
  layout 'publics/header'
  
  def top
    @items = Item.all.page(params[:page]).per(4)
    @genres = Genre.where(status: 'true').all
    @customer = current_customer
  end

  def about
  end
  
end

app/controllers/publics/items_controller.rb
class Publics::ItemsController < ApplicationController
  layout 'publics/header'
  
  def index
    @items = Item.all.page(params[:page]).per(8)
    @customer = current_customer
  end

  def show
    @item = Item.find(params[:id])
    @genres = Genre.all
    @cart = Cart.new
    if @cart.amount == "個数選択"
      redirect_to item_path(item)
    end
    @customer = current_customer
  end

  def genre_items
    @genre = Genre.find(params[:id])
    @items = @genre.items.all
    @items = @items.page(params[:page])
    @customer = current_customer
    @items = @items.page(params[:page])
  end

  private
  def item_params
    params.require(:item).permit(:name, :explanation, :price, :image, :is_status)
  end

end

app/controllers/publics/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Publics::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/publics/orders_controller.rb
class Publics::OrdersController < ApplicationController
  before_action :authenticate_customer!
  layout 'publics/header'
  def new
    @order = Order.new
    @customer = current_customer
    @addresses = @customer.addresses
  end

  def confirm
    @order = Order.new(order_params)
    @customer = current_customer
    @carts = @customer.carts.all
    @cart = current_customer.carts.find_by(item_id: params[:item_id])
    @total = 0
    if params[:order][:order] == "0"
      @order.postcode = @customer.postcode
      @order.address = @customer.address
      @order.name = @customer.last_name + @customer.first_name
    elsif params[:order][:order] == "1"
      @address = Address.find(params[:order][:id])
      @order.postcode = @address.postcode
      @order.address = @address.address
      @order.name = @address.name
    end
    if params[:order][:order] == "2"
			@order.postcode = params[:order][:postcode]
			@order.address = params[:order][:address]
			@order.name = params[:order][:name]
		  Address.create!(customer_id: @customer.id, postcode: @order.postcode, address: @order.address, name: @order.name)
    end
  end

  def complete
    @customer = current_customer
  end

  def create
    @order = Order.new(order_params)
    @order.save
    redirect_to orders_complete_path
    @customer = current_customer
    @carts = @customer.carts.all
    @carts.each do |cart|
      @order_detail = OrderDetail.new
      @order_detail.item_id = cart.item_id
      @order_detail.price = cart.item.price
      @order_detail.amount = cart.amount
      @order_detail.order_id = @order.id
      @order_detail.save
    end
    current_customer.carts.destroy_all
  end

  def index
    @customer = current_customer
    orders = current_customer.orders.all.reverse_order # reverse_orderで逆順で表示する。reverse_orderを使うためにあえてordersに代入している。
    @orders = orders.page(params[:page]).per(6)
    @total = 0
    @customer = current_customer
  end

  def show
    @customer = current_customer
    @order = Order.find(params[:id])
    @total = 0
  end

  private
  def order_params
    params.require(:order).permit(:postcode, :address, :name, :customer_id, :shipping_cost, :pay_money, :pay_way, :status, :shipping_info)
  end

end

app/controllers/publics/passwords_controller.rb
# frozen_string_literal: true

class Publics::PasswordsController < Devise::PasswordsController
  layout 'publics/header'
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/publics/registrations_controller.rb
# frozen_string_literal: true

class Publics::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  layout 'publics/header'

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/publics/sessions_controller.rb
# frozen_string_literal: true

class Publics::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  layout 'publics/header'

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  #退会ユーザーはログイン不可
  before_action :reject_customer, only: [:create]
  protected
    def reject_customer
      @customer = Customer.find_by(email: params[:customer][:email].downcase)
      if @customer
        if (@customer.valid_password?(params[:customer][:encrypted_password]) && (@customer.active_for_authentication? == '退会済み'))
          flash[:error] = "退会済みです。"
          redirect_to new_customer_session_path
        end
      else
        flash[:error] = "必須項目を入力してください"
      end
    end
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/publics/unlocks_controller.rb
# frozen_string_literal: true

class Public::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/publics/orders/comfirm.html.erb
<h2>注文情報確認</h2>

<div class="container">
  <div class="row">

 <div class="col-lg-9">

<table class="table table-bordered">
  <thead class="thead-light">
  <tr>
    <th class="active">商品名</th>
    <th class="active">単価(税込)</th>
    <th class="active">数量</th>
    <th class="active">小計</th>
    <th class="active"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
    <tr>
      <td>
        <%= cart.item.name %>
      </td>
      <td>
        <%= (cart.item.price.* 1.1).round.to_s(:delimited) %>
      </td>
      <td>
        <%= form_with model: cart, url: cart_path(cart), method: :patch, local: true do |f| %>
        <%= f.text_field :amount, auto_focus: true, size:"3" %>
        <%= f.submit "変更", class: "btn btn-primary" %>
        <% end %>
        </td>
      <td><%= (cart.item.price.* 1.1.* cart.amount).round.to_s(:delimited) %></td>
      <td><%= link_to "削除する", cart_path(cart), method: :delete, class: "btn btn-danger" %></td>
      <% sub_total = (cart.item.price.* 1.1.* cart.amount) %>
      <% @total += sub_total %>
    </tr>
    <% end %>
  </tbody>

  <table class="table table-bordered" style="width:350px;">
  </table>


<p>支払方法</p>
    <%= @order.pay_way %>

<p>お届け先</p>
    <%= @order.postcode %><%= @order.address %>
    <%= @order.name %>

</div>

<div class="col-lg-3">
<table class="table">
  <tbody>
  <tr>
    <td class="active">送料</th><td class="active">800</th>
  </tr>
  <tr>
    <td class="active">商品合計</th><td class="active"><%= @total.round.to_s(:delimited) %></th>
  </tr>
  <tr>
    <td class="active">請求額</th><td class="active"><%= (@total.round + 800).to_s(:delimited) %></th>
  </tr>
  </body>
</table>

</div>
</div>
<%= form_with model: @order, url: orders_path, local: true do |f| %>
<%= f.hidden_field :postcode, value: @order.postcode %>
<%= f.hidden_field :address, value: @order.address %>
<%= f.hidden_field :name, value: @order.name %>
<%= f.hidden_field :created_at, value: @order.created_at %>
<%= f.hidden_field :status, value: @order.status %>
<%= f.hidden_field :customer_id, value: current_customer.id %>
<%= f.submit "購入を確定する", class: "btn btn-success" %>
<% end %>

app/views/publics/orders/complete.html.erb
<br>
<br>
<br>
<div class="complete-message">ご購入ありがとうございました！</div>

app/views/publics/orders/confirm.html.erb
<br>
<br>
<br>
<h2>注文情報確認</h2>
<div class="row">
  <div class="col-lg-9">
    <table class="table table-bordered">
      <thead class="thead-light">
        <tr>
          <th style="width:40%;">商品名</th>
          <th>単価(税込)</th>
          <th style="width:18%;">数量</th>
          <th>小計</th>
          <th style="width:10%;"></th>
        </tr>
      </thead>
      <tbody>
        <% @carts.each do |cart| %>
        <tr>
          <td>
            <%= cart.item.name %>
          </td>
          <td>
            <%= (cart.item.price.* 1.1).round.to_s(:delimited) %>
          </td>
          <td>
            <%= form_with model: cart, url: cart_path(cart), method: :patch, local: true do |f| %>
            <%= f.text_field :amount, auto_focus: true, size:"3" %>
            <%= f.submit "変更", class: "btn btn-primary" %>
            <% end %>
          </td>
          <td><%= (cart.item.price.* 1.1.* cart.amount).round.to_s(:delimited) %></td>
          <td><%= link_to "削除する", cart_path(cart), method: :delete, class: "btn btn-danger" %></td>
            <% sub_total = (cart.item.price.* 1.1.* cart.amount) %>
            <% @total += sub_total %>
        </tr>
        <% end %>
      </tbody>
    </table>
    <h4 style="font-size:20px; display: inline-block;">支払方法　　</h4>
      <%= @order.pay_way %>
    <br>
    <h4 style="font-size:20px; display: inline-block;">お届け先　　</h4>
      <%= @order.postcode %><%= @order.address %>
      <%= @order.name %>
  </div>
  <div class="col-lg-3">
    <table class="table table-bordered">
      <tbody>
        <tr>
          <th style="width:40%;">送料</th><td>800</td>
        </tr>
        <tr>
          <th>商品合計</th><td><%= @total.round.to_s(:delimited) %></th>
        </tr>
        <tr>
          <th>請求額</th><td><%= (@total.round + 800).to_s(:delimited) %></th>
        </tr>
      </tbody>
    </table>
  </div>
</div>
<%= form_with model: @order, url: orders_path, local: true do |f| %>
  <%= f.hidden_field :postcode, value: @order.postcode %>
  <%= f.hidden_field :address, value: @order.address %>
  <%= f.hidden_field :name, value: @order.name %>
  <%= f.hidden_field :created_at, value: @order.created_at %>
  <%= f.hidden_field :status, value: @order.status %>
  <%= f.hidden_field :customer_id, value: current_customer.id %>
  <div class="order-success">
  <%= f.submit "購入を確定する", class: "btn btn-success btn-lg" %>
  </div>
<% end %>

app/views/publics/orders/index.html.erb
<br>
<br>
<br>
<h2>注文履歴一覧</h2>
  <table class="table table-bordered">
    <thead class="thead-light">
      <tr>
        <th>注文日</th>
        <th>配送先</th>
        <th>注文商品</th>
        <th>支払金額</th>
        <th>ステータス</th>
        <th>注文詳細</th>
      </tr>
    </thead>
    <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td>
            <%= order.created_at.strftime('%Y/%m/%d') %>
          </td>
          <td>
            <%= order.postcode %><br>
            <%= order.address %><br>
            <%= order.name %>
          </td>
          <td>
            <% order.order_details.each do |order_detail| %> <!--注文した注文商品をeachで出す-->
            <%= order_detail.item.name %><br> <!--注文した注文商品のitemの名前-->
            <% end %>
          </td>
          <td>
            <% order.order_details.each do |order_detail| %>
            <% sub_total = (order_detail.item.price.*1.1* order_detail.amount) %>
            <% @total = sub_total %>
            <% end %>
            <%= (@total + 800).round.to_s(:delimited) %>
          </td>
          <td>
            <%= order.status %>
          </td>
          <td><%= link_to "表示する", order_path(order), class: "btn btn-primary" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="paginate1">
    <%= paginate @orders, class: "paginate" %>
  </div>

app/views/publics/orders/new.html.erb
<br>
<br>
<br>
<h2>注文情報入力</h2>
  <%= form_with model: @order, url: orders_confirm_path, class: 'edit_admins_customer', local: true do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>
    <div class="field">
      <h4 style="font-size:20px;">支払方法</h4>
    </div>
    <div class="field-tag">
    <div><%= f.radio_button :pay_way, "クレジット" %>　クレジット</div>
    <div><%= f.radio_button :pay_way, "銀行振込" %>　銀行振込</div>
    </div>
    <div class="field">
      <h4 style="font-size:20px;">お届け先</h4>
    </div>
    <div class="field-tag">
      <div><%= f.radio_button :order, 0, checked: true %>ご自身の住所<br>
        <%= @customer.postcode %><%= @customer.address %>
        <%= @customer.last_name %><%= @customer.first_name %>
      </div>
      <div><%= f.radio_button :order, 1 %>登録済住所から選択</div>
           <%= f.collection_select :id, @addresses, :id, :shipping_info %>
           
      <div><%= f.radio_button :order, 2 %>新しいお届け先</div>
      
      <div>郵便番号(ハイフンなし)
        <%= f.text_field :postcode, autofocus: true, autocomplete: "postcode" %>
      </div><br>
      <div>住所
        <%= f.text_field :address, autofocus: true, autocomplete: "address" %>
      </div><br>
      <div>宛名
        <%= f.text_field :name, autofocus: true, autocomplete: "name" %>
      </div>
      
      <div class="actions" style="text-align:center">
        <%= f.submit "確認画面へ進む", class: "btn btn-primary" %>
      </div>
    </div>
<% end %>

app/views/publics/orders/show.html.erb
<br>
<br>
<br>
<h2>注文履歴詳細</h2>
<br>
<br>
<div class="row">
  <div class="col-lg-6">
    <h4>注文情報</h4>
    <table class="table table-bordered">
      <tr><th style="font-weight: 100;">注文日</th><td><%= @order.created_at.strftime('%Y/%m/%d') %></td></tr>
      <tr><th style="font-weight: 100;">配送先</th><td><%= @order.postcode %><br><%= @order.address %><br><%= @order.name %></td></tr>
      <tr><th style="font-weight: 100;">支払方法</th><td><%= @order.pay_way %></td></tr>
      <tr><th style="font-weight: 100;">ステータス</th><td><%= @order.status %></td></tr>
    </table>
  </div>
  <div class="col-lg-4">
    <table class="table table-bordered">
    <h4>請求情報</h4>
      <% @order.order_details.each do |order_detail| %>
      <% sub_total = (order_detail.item.price.*1.1.* order_detail.amount) %>
      <% @total += sub_total %>
      <% end %>
      <tr><th style="font-weight: 100;">商品合計</th><td><%= (@total).round.to_s(:delimited) %></td></tr>
      <tr><th style="font-weight: 100;">配送料</th><td>800</td></tr>
      <tr><th style="font-weight: 800;">ご請求額</th><td><%= (@total + 800).round.to_s(:delimited) %></td></tr>
    </table>
  </div>
</div>
<div class="row">
  <div class="col-lg-8">
    <h4>注文内容</h4>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th style="width: 70%;">商品</th>
            <th>単価（税込）</th>
            <th>個数</th>
            <th>小計</th>
          </tr>
        </thead>
        <tbody>
          <% @order.order_details.each do |order_detail| %>
            <tr>
              <td>
                <%= order_detail.item.name %>
              </td>
              <td>
                <%= (order_detail.item.price.* 1.1).round.to_s(:delimited) %>
              </td>
              <td>
                <%= order_detail.amount %>
              </td>
              <td>
                <%= (order_detail.price.* 1.1.* order_detail.amount).round.to_s(:delimited)%>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>