config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: :all
  devise_scope :admin do
  get 'admins/sign_in',to: 'admins/sessions#new'
  post 'admins/sign_in',to: 'admins/sessions#create'
  delete 'admins/sign_out',to: 'admins/sessions#destroy'
  end

  devise_for :customers, skip: :all
  devise_scope :customer do
  get 'customers/sign_up', to: 'publics/registrations#new'
  post 'customers/sign_up', to: 'publics/registrations#create'
  patch 'customers', to: 'publics/registrations#update'
  put 'customers', to: 'publics/registrations#update'
  delete 'customers', to: 'publics/registrations#update'
  get 'customers/sign_in',to: 'publics/sessions#new'
  post 'customers/sign_in',to: 'publics/sessions#create'
  delete 'customers/sign_out',to: 'publics/sessions#destroy'
  get 'customers/password/new', to: 'publics/passwords#new'
  get 'customers/password/edit', to: 'publics/passwords#edit'
  patch 'customers/password', to: 'publics/passwords#update'
  put 'customers/password', to: 'publics/passwords#update'
  get 'login' => 'publics/sessions#new', as: :new_customer_session
  post 'login' => 'publics/sessions#create', as: :customer_session
  get 'signup' => 'publics/registrations#new', as: :new_customer_registration
  post 'signup' => 'publics/registrations#create', as: :customer_registration
  get 'password' => 'publics/passwords#new', as: :new_customer_password
  get 'password/edit' => 'publics/passwords#edit', as: :edit_customer_password
  post 'password' => 'publics/passwords#create', as: :customer_password
  #パスワード変更
  get 'password/:id' => 'publics/registrations#edit', as: :edit_customer_registration
  patch "password/:id" => 'publics/registrations#update', as: :update_customer_registration

  end

  root "publics/homes#top"
  get "/about" => "publics/homes#about"
  get "/customers/unsubscribe" => "publics/customers#unsubscribe"
  patch "/customers/withdraw" => "publics/customers#withdraw"
  scope module: :publics do
  get "/customers/unsubscribe" => "customers#unsubscribe"
  patch "/customers/withdraw" => "customers#withdraw"
  get 'password/edit' => 'passwords#edit'
  resources :items, only:[:index, :show]
  get 'genre_items/:id' => "items#genre_items", as: "genre_items"
  get "/orders/complete" => "orders#complete"
  post "/orders/confirm" => "orders#confirm"
  resources :orders, only:[:new, :create, :index, :show]
  delete "/carts/destroy_all" => "carts#destroy_all"
  resources :carts, only:[:index, :update, :destroy, :create]
  resources :customers, only:[:edit, :show, :update]
  resources :addresses, only:[:index, :create, :edit, :destroy, :update]
  end

  namespace :admins do
  get "/" => "homes#top"
  resources :customers, only:[:index, :show, :edit, :update]
  resources :genres, only:[:index, :create, :edit, :update]
  resources :orders, only:[:index, :show, :update]
  resources :items, only:[:index, :new, :create, :show, :edit, :update]
  resources :order_details, only: [:update]
  patch "/orders/:order_id/order_details/:id" => "order_details#update"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items

  enum is_status: {
    有効: true,
    無効: false
  }

  # バリデーション すでに存在しているジャンルと同じジャンル名であれば保存されない
  validates :name, uniqueness: true, presence: true
end

app/controllers/admins/genres_controller.rb
class Admins::GenresController < ApplicationController
  before_action :authenticate_admin!
  layout 'admins/header'

  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    @genres = Genre.all
    if @genre.save
      redirect_to admins_genres_path
    else
      render :index
    end
  end

  def show
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admins_genres_path
    else
      render :edit
    end
  end

  private
  def genre_params
    params.require(:genre).permit(:name, :is_status)
  end

end

app/helpers/admins/genres_helper.rb
module Admins::GenresHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/admins/genres/edit.html.erb
<h2 style="margin: 30px 0 50px 100px ;">ジャンル編集</h2>
  <div class="row">
    <%= form_with model: @genre, url: admins_genre_path(@genre), method: :patch, local: true do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
      <div class="genre-container">
        <p>ジャンル</p>
          <%= f.text_field :name, class: "form-control" %>
        <div class="status-btn">
          <%= f.radio_button :is_status, '有効' %>有効
        </div>
        <div class="status-btn">
          <%= f.radio_button :is_status, '無効' %>無効
        </div>
          <%= f.submit "変更を保存する", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>

app/views/admins/genres/index.html.erb
<h2 style="margin: 30px 0 50px 100px ;">ジャンル一覧・追加</h2>

  <div class="row">
    <%= form_with model: @genre, url: admins_genres_path, local: true do |f| %>
    <%= render 'layouts/error_messages', model: @genre %>
    <div class="genre-container">
      <p>ジャンル</p>
        <%= f.text_field :name, class: "form-control" %>
      <div class="status-btn">
        <%= f.radio_button :is_status, '有効' %>有効
      </div>
      <div class="status-btn">
        <%= f.radio_button :is_status, '無効' %>無効
      </div>
        <%= f.submit "追加", class: "btn btn-primary" %>
      </div>
    <% end %>
      
    <table class="table table-hover table-inverse" style = "width: 600px; margin-top: 30px;">
      <thead>
        <tr>
          <th>ジャンル</th>
          <th>状態</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @genres.each do |genre| %>
        <tr>
          <td><%= genre.name %></td>
          <td><%= genre.is_status %></td>
          <td><%= link_to "編集する", edit_admins_genre_path(genre), class: "glyphicon glyphicon-pencil btn btn-success" %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>