config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: :all
  devise_scope :admin do
  get 'admins/sign_in',to: 'admins/sessions#new'
  post 'admins/sign_in',to: 'admins/sessions#create'
  delete 'admins/sign_out',to: 'admins/sessions#destroy'
  end

  devise_for :customers, skip: :all
  devise_scope :customer do
  get 'customers/sign_up', to: 'publics/registrations#new'
  post 'customers/sign_up', to: 'publics/registrations#create'
  patch 'customers', to: 'publics/registrations#update'
  put 'customers', to: 'publics/registrations#update'
  delete 'customers', to: 'publics/registrations#update'
  get 'customers/sign_in',to: 'publics/sessions#new'
  post 'customers/sign_in',to: 'publics/sessions#create'
  delete 'customers/sign_out',to: 'publics/sessions#destroy'
  get 'customers/password/new', to: 'publics/passwords#new'
  get 'customers/password/edit', to: 'publics/passwords#edit'
  patch 'customers/password', to: 'publics/passwords#update'
  put 'customers/password', to: 'publics/passwords#update'
  get 'login' => 'publics/sessions#new', as: :new_customer_session
  post 'login' => 'publics/sessions#create', as: :customer_session
  get 'signup' => 'publics/registrations#new', as: :new_customer_registration
  post 'signup' => 'publics/registrations#create', as: :customer_registration
  get 'password' => 'publics/passwords#new', as: :new_customer_password
  get 'password/edit' => 'publics/passwords#edit', as: :edit_customer_password
  post 'password' => 'publics/passwords#create', as: :customer_password
  #パスワード変更
  get 'password/:id' => 'publics/registrations#edit', as: :edit_customer_registration
  patch "password/:id" => 'publics/registrations#update', as: :update_customer_registration

  end

  root "publics/homes#top"
  get "/about" => "publics/homes#about"
  get "/customers/unsubscribe" => "publics/customers#unsubscribe"
  patch "/customers/withdraw" => "publics/customers#withdraw"
  scope module: :publics do
  get "/customers/unsubscribe" => "customers#unsubscribe"
  patch "/customers/withdraw" => "customers#withdraw"
  get 'password/edit' => 'passwords#edit'
  resources :items, only:[:index, :show]
  get 'genre_items/:id' => "items#genre_items", as: "genre_items"
  get "/orders/complete" => "orders#complete"
  post "/orders/confirm" => "orders#confirm"
  resources :orders, only:[:new, :create, :index, :show]
  delete "/carts/destroy_all" => "carts#destroy_all"
  resources :carts, only:[:index, :update, :destroy, :create]
  resources :customers, only:[:edit, :show, :update]
  resources :addresses, only:[:index, :create, :edit, :destroy, :update]
  end

  namespace :admins do
  get "/" => "homes#top"
  resources :customers, only:[:index, :show, :edit, :update]
  resources :genres, only:[:index, :create, :edit, :update]
  resources :orders, only:[:index, :show, :update]
  resources :items, only:[:index, :new, :create, :show, :edit, :update]
  resources :order_details, only: [:update]
  patch "/orders/:order_id/order_details/:id" => "order_details#update"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :order_details, dependent: :destroy
  has_many :carts, dependent: :destroy
  belongs_to :genre, optional: true
  attachment :image

  enum is_status: {
    '販売中': true,
    '販売中止': false
  }

  validates :name, :explanation, :price, :genre_id, :is_status, presence: true
end

app/controllers/admins/items_controller.rb
class Admins::ItemsController < ApplicationController
  before_action :authenticate_admin!
  layout 'admins/header'
  
  def index
    @items = Item.all.page(params[:page]).per(10)
    @genres= Genre.all
  end

  def new
    @item = Item.new
    @genres= Genre.all
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admins_item_path(@item)
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admins_item_path(@item)
    else
      render :edit
    end
  end

  private
  def item_params
    params.require(:item).permit(:name, :explanation, :price, :image, :is_status, :genre_id)
  end
end

app/controllers/publics/items_controller.rb
class Publics::ItemsController < ApplicationController
  layout 'publics/header'
  
  def index
    @items = Item.all.page(params[:page]).per(8)
    @customer = current_customer
  end

  def show
    @item = Item.find(params[:id])
    @genres = Genre.all
    @cart = Cart.new
    if @cart.amount == "個数選択"
      redirect_to item_path(item)
    end
    @customer = current_customer
  end

  def genre_items
    @genre = Genre.find(params[:id])
    @items = @genre.items.all
    @items = @items.page(params[:page])
    @customer = current_customer
    @items = @items.page(params[:page])
  end

  private
  def item_params
    params.require(:item).permit(:name, :explanation, :price, :image, :is_status)
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/admins/items/edit.html.erb
<h2 style="margin: 30px 0 100px 100px ;">商品編集</h2>
  <div class="row">
    <%= form_with model: @item, url: admins_item_path(@item), local: true do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
    <div class="col-xs-4">
      <div class="item_image">
		    <%= attachment_image_tag @item, :image, class: "img", fallback: "no-image.png", size:"300x300" %>
				<%= f.attachment_field :image %>
			</div>
			<!-- 画像プレビュー -->
			<script>
			   $(function(){
			     //inputのidから情報を取得
		       	$('#item_image').on('change', function (e) {
		       	  // ココから既存の画像のurlの取得
		       		var reader = new FileReader();
		    		reader.onload = function (e) {
		    			$(".image").attr('src', e.target.result);
		    		}
		    		// ココまで
		    		reader.readAsDataURL(e.target.files[0]);
		    		// 取得したurlにアップロード画像のurlを取得
	          });
	        });
		    </script>
    </div>
    
    <div class="col-xs-3">
      <h4>商品名</h4>
        <%= f.text_field :name, class:"form-control" %>
        
      <h4>商品説明</h4>
        <%= f.text_area :explanation, class:"form-control" %>
  
      <h4>ジャンル</h4>
        <%= f.collection_select(:genre_id, Genre.all, :id, :name, {prompt: "選択してください"}) %>
        
      <h4>税抜価格</h4>
      <div class="item-price-container">
        <div><%= f.text_field :price, class:"form-control" %></div>
        <div class="item-price">円</div>
      </div>
      
      <h4>販売ステータス</h4>
        <%= f.select :is_status, [['販売中','販売中'],['販売中止', '販売中止']], {prompt: "選択してください"} %>
        <%= f.submit "変更を保存", class: "btn btn-primary" %>
    <% end %>
    </div>
  </div>

app/views/admins/items/index.html.erb
  <div class="row">
	  <div class="col-xs-11">
		  <h2 style="margin: 30px 0 30px 100px;">商品一覧</h2>
		    <div class="add-item">
		      <%= link_to (new_admins_item_path) do %>
			      <i class="fas fa-cheese"></i>新規登録
          <% end %>
          <table class="table table-hover table-inverse">
            <thead>
              <tr>
                <th>商品ID</th>
                <th>商品名</th>
                <th>税抜価格</th>
                <th>ジャンル</th>
                <th>ステータス</th>
              </tr>
              </thead>
              <tbody>
              <% @items.each do |item| %>
                <tr>
                  <td><%= item.id %></td>
                  <td><%= link_to item.name, admins_item_path(item.id) %></td>
                  <td><%= item.price.to_s(:delimited) %></td>
                  <td><%= item.genre.name %></td>
                  <td><%= item.is_status %></td>
                </tr>
              <% end %>
              </tbody>
            <%= paginate @items %>
          </div>
        </div>
      </div>

app/views/admins/items/new.html.erb
<h2 style="margin: 30px 0 100px 100px;">商品新規登録</h2>
  <div class="row">
    <%= form_with model: @item, url: admins_items_path, local: true do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
    <div class="col-xs-5" >
      <div class="item_image">
		    <%= attachment_image_tag @item, :image, class: "img", fallback: "no-image.png", size:"300x300" %>
				<%= f.attachment_field :image %>
			</div>
			<!-- 画像プレビュー -->
			<script>
			   $(function(){
			     //inputのidから情報を取得
		       	$('#item_image').on('change', function (e) {
		       	  // ココから既存の画像のurlの取得
		       		var reader = new FileReader();
		    		reader.onload = function (e) {
		    			$(".image").attr('src', e.target.result);
		    		}
		    		// ココまで
		    		reader.readAsDataURL(e.target.files[0]);
		    		// 取得したurlにアップロード画像のurlを取得
	          });
	        });
		    </script>
      </div>

      <div class="col-xs-7">
        <h4>商品名</h4>
        <div class="item-form">
          <%= f.text_field :name, class:"form-control" %>
        </div>

        <h4>商品説明</h4>
        <div class="item-explanation">
          <%= f.text_area :explanation, class:"form-control"  %>
        </div>

        <h4>ジャンル</h4>
        <div class="item-genre">
          <%= f.collection_select(:genre_id, Genre.all, :id, :name, {prompt: "選択してください"}) %>
        </div>

        <h4>税抜価格</h4>
        <div class="item-price-container">
          <div><%= f.text_field :price, class:"form-control" %></div>
          <div class="item-price">円</div>
        </div>

        <h4>販売ステータス</h4>
        <div class="item-status">
          <%= f.select :is_status, [['販売中','販売中'],['販売中止', '販売中止']], {prompt: "選択してください"} %>
        </div>

        <div style="padding-top:10px;">
          <%= f.submit "新規登録", class: "btn btn-primary" %>
        </div>
      </div>
      <% end %>
    </div>

app/views/admins/items/show.html.erb
 <h2 style="margin: 30px 0 100px 100px ;">商品詳細</h2>
  <div class="row">
    <div class="col-xs-4">
      <div>
        <%= attachment_image_tag @item, :image, size: "250x250", format: 'jpeg', fallback: "no-image.png" %>
      </div>
    </div>
    
    <div class="col-xs-５">
      <div class="item-field">
        <p>商品名  <%= @item.name %></p></br>
      </div>
      <div class="item-field">
        <p>商品説明  <%= @item.explanation %></p></br>
      </div>
      <div class="item-field">
        <p>ジャンル  <%= @item.genre.name %></p></br>
      </div>
      <div class="item-field">
        <p>
          税込価格 (税抜価格）
          <%= (@item.price.* 1.1).round.to_s(:delimited) %>
          (<%= @item.price.to_s(:delimited) %>)
          <span>円</span>
        </p></br>
      </div>
    </div>
    <div class="item-field">
      <p>販売ステータス　　<%= @item.is_status %></p>
    </div>
    <div>
      <%= link_to "編集する", edit_admins_item_path, class: "btn btn-primary" %>
    </div>
  </div>