config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: :all
  devise_scope :admin do
  get 'admins/sign_in',to: 'admins/sessions#new'
  post 'admins/sign_in',to: 'admins/sessions#create'
  delete 'admins/sign_out',to: 'admins/sessions#destroy'
  end

  devise_for :customers, skip: :all
  devise_scope :customer do
  get 'customers/sign_up', to: 'publics/registrations#new'
  post 'customers/sign_up', to: 'publics/registrations#create'
  patch 'customers', to: 'publics/registrations#update'
  put 'customers', to: 'publics/registrations#update'
  delete 'customers', to: 'publics/registrations#update'
  get 'customers/sign_in',to: 'publics/sessions#new'
  post 'customers/sign_in',to: 'publics/sessions#create'
  delete 'customers/sign_out',to: 'publics/sessions#destroy'
  get 'customers/password/new', to: 'publics/passwords#new'
  get 'customers/password/edit', to: 'publics/passwords#edit'
  patch 'customers/password', to: 'publics/passwords#update'
  put 'customers/password', to: 'publics/passwords#update'
  get 'login' => 'publics/sessions#new', as: :new_customer_session
  post 'login' => 'publics/sessions#create', as: :customer_session
  get 'signup' => 'publics/registrations#new', as: :new_customer_registration
  post 'signup' => 'publics/registrations#create', as: :customer_registration
  get 'password' => 'publics/passwords#new', as: :new_customer_password
  get 'password/edit' => 'publics/passwords#edit', as: :edit_customer_password
  post 'password' => 'publics/passwords#create', as: :customer_password
  #パスワード変更
  get 'password/:id' => 'publics/registrations#edit', as: :edit_customer_registration
  patch "password/:id" => 'publics/registrations#update', as: :update_customer_registration

  end

  root "publics/homes#top"
  get "/about" => "publics/homes#about"
  get "/customers/unsubscribe" => "publics/customers#unsubscribe"
  patch "/customers/withdraw" => "publics/customers#withdraw"
  scope module: :publics do
  get "/customers/unsubscribe" => "customers#unsubscribe"
  patch "/customers/withdraw" => "customers#withdraw"
  get 'password/edit' => 'passwords#edit'
  resources :items, only:[:index, :show]
  get 'genre_items/:id' => "items#genre_items", as: "genre_items"
  get "/orders/complete" => "orders#complete"
  post "/orders/confirm" => "orders#confirm"
  resources :orders, only:[:new, :create, :index, :show]
  delete "/carts/destroy_all" => "carts#destroy_all"
  resources :carts, only:[:index, :update, :destroy, :create]
  resources :customers, only:[:edit, :show, :update]
  resources :addresses, only:[:index, :create, :edit, :destroy, :update]
  end

  namespace :admins do
  get "/" => "homes#top"
  resources :customers, only:[:index, :show, :edit, :update]
  resources :genres, only:[:index, :create, :edit, :update]
  resources :orders, only:[:index, :show, :update]
  resources :items, only:[:index, :new, :create, :show, :edit, :update]
  resources :order_details, only: [:update]
  patch "/orders/:order_id/order_details/:id" => "order_details#update"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def shipping_info
    postcode + " " + " " + address + " " + " "+ name
  end

  validates :address, :name, presence: true
  validates :postcode, presence: true # format: { with: /\A\d{7}\z/ }
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :item
  belongs_to :customer

  validates :amount, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, dependent: :destroy
  has_many :carts, dependent: :destroy
  has_many :addresses, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postcode, presence: true
  validates :address, presence: true
  validates :phonenumber, presence: true
  validates :email, presence: true
  validates :encrypted_password, presence: true

  enum is_deleted: {
    有効: false,
    退会済み: true
  }
  #deletedがfalse(有効)の場合はログイン可能
  def active_for_authentication?
  super && (self.is_deleted == '有効' )
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items

  enum is_status: {
    有効: true,
    無効: false
  }

  # バリデーション すでに存在しているジャンルと同じジャンル名であれば保存されない
  validates :name, uniqueness: true, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :order_details, dependent: :destroy
  has_many :carts, dependent: :destroy
  belongs_to :genre, optional: true
  attachment :image

  enum is_status: {
    '販売中': true,
    '販売中止': false
  }

  validates :name, :explanation, :price, :genre_id, :is_status, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details, dependent: :destroy
  belongs_to :customer

  validates :postcode, :address, :name, presence: true

   enum pay_way: {
    クレジット: 0,
    銀行振込: 1
  }

   enum status: {
    入金待ち: 0,
    入金確認: 1,
    製作中: 2,
    発送準備中: 3,
    発送済み: 4
  }

  #validates :order, acceptance: true
  #validates :order, presence: true
  #validates :order, inclusion: {in: [0, 1, 2]}
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order

  validates :amount, :price, presence: true
  validates :making_status, presence: true

  enum making_status: {
    製作不可: 0,
    製作待ち: 1,
    製作中: 2,
    製作完了: 3
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller? #(customer側の新規登録情報を保存)

  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :admin
      admins_sign_in_path # ログアウト後に遷移するpathを設定(admin側)
    else
      root_path # ログアウト後に遷移するpathを設定(customer側)
    end
  end

  def after_sign_in_path_for(resource)
    case resource
      when Admin
        admins_path # ログイン後に遷移するpathを設定(admin側)
      when Customer
        root_path  # ログイン後に遷移するpathを設定(customer側)
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :first_name_kana, :last_name_kana, :postcode, :address, :phonenumber])
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admins/genres_helper.rb
module Admins::GenresHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/order_details_helper.rb
module OrderDetailsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/admins/header.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Shop1</title>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>
        <script src="https://kit.fontawesome.com/fc6aa7a24c.js" crossorigin="anonymous"></script>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <title>ながのCAKE</title>
    </head>
    <body>
        <header>
            <nav class="navbar navbar-default" style="height:60px;">
                <div class="container-fluid" style="height:60px;">
                    <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navigation">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <h6><a href="/"></a></h6>
                    <div class="header-logo">ながのCAKE</div>
                    </div>
                    <div class="header-nav-div">
                        <% if admin_signed_in? %>
                            <li class="header-nav">
                                <%= link_to "商品一覧", admins_items_path, class: "btn-square-so-pop" %>
                            </li>
                            <li class="header-nav">
                                <%= link_to "会員一覧", admins_customers_path, class: "btn-square-so-pop" %>
                            </li>
                            <li class="header-nav">
                                <%= link_to "注文履歴一覧", admins_orders_path, class: "btn-square-so-pop" %>
                            </li>
                            <li class="header-nav">
                                <%= link_to "ジャンル一覧", admins_genres_path, class: "btn-square-so-pop" %>
                            </li>
                            <li class="header-nav">
                                <%= link_to "ログアウト", admins_sign_out_path, method: :delete, class: "btn-square-so-pop" %>
                            </li>
                        <% else %>
                            <li class="header-nav">
                                <%= link_to "About", about_path, class: "btn-square-so-pop" %>
                            </li>
                            <li class="header-nav">
                                <%= link_to "商品一覧", root_path, class: "btn-square-so-pop" %>
                            </li>
                            <li class="header-nav">
                                <%= link_to "新規登録", customers_sign_up_path, class: "btn-square-so-pop" %>
                            </li>
                            <li class="header-nav">
                                <%= link_to "ログイン", customers_sign_in_path, class: "btn-square-so-pop" %>
                            </li>
                        <% end %>
                    </div>
                </div>
            </nav>
        </header>
        <div class="container">
            <%= yield %>
        </div>
    </body>
</html>